sensor.fibaro_system_fgd212_dimmer_2_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgd212_dimmer_2_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgd212_dimmer_2_exporting:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgd212_dimmer_2_system:
  ignored: true
  polling_intensity: 0
switch.fibaro_system_fgs223_double_relay_switch:
  ignored: false
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_access_control_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_level_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_type_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_sourcenodeid_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_access_control:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_exporting:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_exporting:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_exporting_2:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_heat:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgs223_double_relay_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_power_management:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_access_control:
  ignored: true
  polling_intensity: 0
binary_sensor.back_door:
  ignored: false
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_level_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_type_2:
  ignored: true
  polling_intensity: 0
binary_sensor.ecolink_door_window_sensor_sensor:
  ignored: false
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_burglar:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.basement_flooding:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_level_3:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_type_3:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_level_4:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_alarm_type_4:
  ignored: true
  polling_intensity: 0
sensor.ecolink_garage_door_alarm_level_5:
  ignored: true
  polling_intensity: 0
sensor.ecolink_garage_door_alarm_type_5:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_flood:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpe_f_wall_plug_gen5_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpe_f_wall_plug_gen5_exporting:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpe_f_wall_plug_gen5_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_access_control_3:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_burglar_3:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_power_management_3:
  ignored: true
  polling_intensity: 0
sensor.ecolink_door_window_sensor_sourcenodeid_3:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_alarm_level_3:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_alarm_type_3:
  ignored: true
  polling_intensity: 0
sensor.philio_technology_corp_ph_pat02_eu_flood_multisensor_3in1_temperature:
  ignored: false
  polling_intensity: 0
sensor.hauppage_furnace_flood_sensor_battery_level:
  ignored: false
  polling_intensity: 0
binary_sensor.boiler_flood_sensor:
  ignored: false
  polling_intensity: 0
